command_key = ":"
initial_screen = "library"
use_nerdfont = true
flip_status_indicators = true
backend = "pulseaudio"
audio_cache = false
volnorm = false
default_keybindings = true
notify = true
bitrate = 320
gapless = false
shuffle = true
repeat = "playlist"
playback_state = "Paused"
library_tabs = ["playlists"]
cover_max_scale = 1.0
hide_display_names = true
statusbar_format = "%artists - %title"
[notification_format]
title = "%title"
body = "%artists"
[track_format]
left = "%title - %album"
center = "%artists"
right = "%duration"
[theme]
background = "#333333"
primary = "#e0e0e0"
secondary = "#cc77cc"
title = "#ffcc00"
playing = "#ffcc00"
playing_selected = "#ffcc00"
playing_bg = "#333333"
highlight = "#e0e0e0"
highlight_bg = "#666600"
error = "#333333"
error_bg = "#bb3333"
statusbar = "#e0e0e0"
statusbar_progress = "#ffcc00"
statusbar_bg = "#333333"
cmdline = "#333333"
cmdline_bg = "#e0e0e0"
search_match = "#cc77cc"
